### ISSUE TITLE
nyuu doent work due to node-yencode doesn't build on macOS Sonoma (14.6.1)

### ISSUE THREAD

**Issue by sspilleman** [animetosho/Nyuu#133]
Hi,

I get an error: Error: Cannot find module './build/Release/yencode.node'
`node-yencode` doesn't build. I created a ticket on that repo.

Sander

**Comment by sspilleman** [comment]
Closed due to issues resolved with node-yencode

**Comment by sspilleman** [comment]
Closed due to issues resolved with node-yencode
